### ISSUE TITLE
Error rather than degrade if inference fails

### ISSUE THREAD

**Issue by banool** [ThalaLabs/surf#73]
One thing I notice is if you don't have the right module ID the type inference still proceeds but it misses a lot of information. 

For example, this gives me rich type information:
```
type ABITAble = DefaultABITable & {
  "0x296102a3893d43e11de2aa142fbb126377120d7d71c246a2f95d5b4f3ba16b30::chess": typeof CHESS_ABI;
};
```

But this doesn't:
```
type ABITAble = DefaultABITable & {
  "0x296102a3893d43e11de2aa142fbb126377120d7d71c246a2f95d5b4f3ba16b30::Chess": typeof CHESS_ABI;
};
```

I would rather the second case be an error rather than it just degrade silently.

**Comment by banool** [comment]
Seems much better to me!

**Comment by SamuelQZQ** [comment]
@banool We have release the change in 1.6.0. Now the ABITable should be a list:
```
import { DefaultABITable } from "@thalalabs/surf";
import { createSurfClient } from '@thalalabs/surf';
import { Aptos } from '@aptos-labs/ts-sdk';

type ABITAble = [
  ...DefaultABITable,
  ...[
    typeof FIXED_POINT64_ABI
  ]
];

const client = createSurfClient<ABITAble>(new Aptos());
```

And btw, for enhanced security, we now publish all packages, including Surf, on Github Packages instead of npm registry. To install Surf, now you need to add a ﻿`.npmrc` config. You can find more details in README.md. Feel free to share your feedback.
